In [85]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
import pandas as pd
from transformers import AutoTokenizer, DistilBertModel
import numpy as np

In [86]:
# create a simple torch model with 1 fully connected layer

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(768, 2)

    def forward(self, x):
        # apply relu on the output of the fully connected layer
        x = F.relu(self.fc1(x))
        return x

In [87]:
words = [
    "apple", "book", "car", "dog", "cat", "house", "tree", "friend", "time", "money",
    "heart", "sun", "moon", "sky", "water", "fire", "earth", "flower", "city", "music",
    "child", "parent", "school", "job", "love", "smile", "day", "night", "star", "cloud",
    "bird", "fish", "food", "computer", "phone", "internet", "coffee", "tea", "shoes", "hat",
    "dream", "goal", "team", "game", "hope", "fear", "joy", "anger", "peace", "war",
    "friendship", "family", "health", "beauty", "knowledge", "power", "nature", "history", "science",
    "art", "happiness", "sadness", "color", "mind", "body", "soul", "memory", "experience", "idea",
    "faith", "truth", "lie", "problem", "solution", "question", "answer", "light", "darkness", "wind",
    "rain", "snow", "smell", "taste", "touch", "sound", "silence", "joy", "freedom", "future",
    "past", "present", "purpose", "journey", "adventure", "discovery", "challenge", "victory", "defeat"
]

most_common_words = []

# remove duplicates
words = list(set(words))
# most_common_words = list(set(most_common_words))

print(len(words))
print(len(most_common_words))

assert len(list(set(words + most_common_words))) == len(words) + len(most_common_words)

97
0


In [88]:
non_words = [
    "run", "jump", "eat", "sleep", "think", "happy", "fast", "slow", "beautiful", "smart",
    "quickly", "easily", "always", "never", "under", "over", "beside", "between", "through", "with",
    "and", "but", "or", "because", "although", "well", "yes", "no", "oh", "wow", "ouch",
    "go", "come", "stop", "start", "win", "lose", "hot", "cold", "loud", "soft",
    "bright", "dark", "high", "low", "near", "far", "big", "small", "old", "new",
    "first", "last", "next", "previous", "good", "bad", "happy", "sad", "rich", "poor",
    "early", "late", "hard", "easy", "simple", "complex", "right", "wrong", "true", "false",
    "up", "down", "in", "out", "on", "off", "up", "down", "here", "there",
    "now", "then", "today", "tomorrow", "yesterday", "soon", "later", "before", "after", "while",
    "once", "twice", "thrice", "nevertheless", "however", "suddenly", "finally", "quickly", "slowly", "nowadays",
    "some", "many", "few", "most", "none", "all", "each", "every", "somebody", "nobody",
    "something", "nothing", "somewhere", "nowhere", "anywhere", "everywhere", "this", "that", "these", "those",
    "which", "what", "who", "whom", "whose", "where", "when", "why", "how", "whether",
    "if", "unless", "because", "since", "although", "though", "while", "before", "after", "when",
    "and", "or", "but", "nor", "for", "so", "yet", "either", "neither", "however"
]

# remove duplicates
non_words = list(set(non_words))

print(len(non_words))


137


In [89]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model = DistilBertModel.from_pretrained("distilbert-base-uncased")

In [90]:
# create a function that takes a list of words and returns a list of embeddings
def get_embeddings(words):
    embeddings = []

    for word in words:
        input_ids = torch.tensor(tokenizer.encode(word)).unsqueeze(0)
        outputs = model(input_ids)
        last_hidden_states = outputs[0]
        embeddings.append(torch.mean(last_hidden_states[0][1:-1], dim=0).tolist())
    
    assert len(embeddings) == len(words)
    return embeddings

embeddings = get_embeddings(words)
most_common_embeddings = get_embeddings(most_common_words)
non_embeddings = get_embeddings(non_words)

In [91]:
# slice the lists into training and test sets
words_train = words[:int(len(words)*0.8)]
words_test = words[int(len(words)*0.8):]
embeddings_train = embeddings[:int(len(embeddings)*0.8)]
embeddings_test = embeddings[int(len(embeddings)*0.8):]

most_common_words_train = most_common_words[:int(len(most_common_words)*0.8)]
most_common_words_test = most_common_words[int(len(most_common_words)*0.8):]
most_common_embeddings_train = most_common_embeddings[:int(len(most_common_embeddings)*0.8)]
most_common_embeddings_test = most_common_embeddings[int(len(most_common_embeddings)*0.8):]

non_words_train = non_words[:int(len(non_words)*0.8)]
non_words_test = non_words[int(len(non_words)*0.8):]
non_embeddings_train = non_embeddings[:int(len(non_embeddings)*0.8)]
non_embeddings_test = non_embeddings[int(len(non_embeddings)*0.8):]

# create a dataframe with the training and test sets
df_train = pd.DataFrame({
    'word': words_train + most_common_words_train + non_words_train,
    'embedding': embeddings_train + most_common_embeddings_train + non_embeddings_train,
    'label': [1]*len(words_train) + [1]*len(most_common_words_train) + [0]*len(non_words_train)
})

df_test = pd.DataFrame({
    'word': words_test + most_common_words_test + non_words_test,
    'embedding': embeddings_test + most_common_embeddings_test + non_embeddings_test,
    'label': [1]*len(words_test) + [1]*len(most_common_words_test) + [0]*len(non_words_test)
})

# shuffle the dataframes
# df_train = df_train.sample(frac=1).reset_index(drop=True)
# df_test = df_test.sample(frac=1).reset_index(drop=True)

print(df_train[:5])
print(df_train[-5:])
print(df_test[:5])
print(df_test[-5:])

    word                                          embedding  label
0    job  [0.14350789785385132, -0.15940922498703003, -0...      1
1   body  [0.7147403359413147, -0.1555342972278595, 0.31...      1
2  faith  [0.6398938298225403, 0.13858512043952942, -0.1...      1
3  earth  [0.26693275570869446, 0.4444328844547272, -0.1...      1
4  water  [0.2036658525466919, 0.2685178220272064, -0.28...      1
          word                                          embedding  label
181   somebody  [-0.007474187761545181, -0.06840874254703522, ...      0
182         in  [-0.8657609224319458, -0.5856645703315735, -0....      0
183         on  [-0.11932921409606934, -0.3286181688308716, -0...      0
184      later  [-0.2563585937023163, -0.453279972076416, -0.1...      0
185  something  [-0.15402115881443024, -0.17753523588180542, -...      0
     word                                          embedding  label
0    mind  [0.38985970616340637, 0.27778860926628113, -0....      1
1   smile  [-0.117154628

In [92]:
class CustomDataset(Dataset):
    def __init__(self, tokenized_texts, labels):
        self.tokenized_texts = torch.tensor(tokenized_texts)
        self.labels = torch.tensor(labels)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.tokenized_texts[idx], self.labels[idx]

In [93]:
train_dataset = CustomDataset(df_train['embedding'], df_train['label'])
test_dataset = CustomDataset(df_test['embedding'], df_test['label'])

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=True)

In [94]:
# train the model
net = Net()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.003)

num_epochs = 100
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
net.to(device)

for epoch in range(num_epochs):
    net.train()
    combined_loss = 0
    for batch in train_loader:
        # get data to GPU if possible
        data = batch[0].to(device=device)
        targets = batch[1].to(device=device)

        # forward
        scores = net(data)
        loss = criterion(scores, targets)
        combined_loss += loss.item()

        # backward
        optimizer.zero_grad()
        loss.backward()

        # gradient descent or adam step
        optimizer.step()
    
    # print initial loss
    if epoch == 0:
        print(f'Initial loss: {combined_loss/len(train_loader)}')
        
    # print average loss per epoch every 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f'Epoch {epoch + 1}, loss={combined_loss/len(train_loader)}')
        # print(combined_loss / len(train_loader))



Initial loss: 0.5994711021582285
Epoch 10, loss=0.051087685860693455
Epoch 20, loss=0.02002626455699404
Epoch 30, loss=0.01178085602199038
Epoch 40, loss=0.007276703487150371
Epoch 50, loss=0.0053643395367544144
Epoch 60, loss=0.003953498953099673
Epoch 70, loss=0.003117616792830328
Epoch 80, loss=0.002558116990257986
Epoch 90, loss=0.0020333628490334377
Epoch 100, loss=0.0017162608904376004


A lot of variance over different runs
Best so far: 0.001

In [95]:
# evaluate the model
def check_accuracy(loader, model):
    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():
        for batch in loader:
            # get data to GPU if possible
            data = batch[0].to(device=device)
            targets = batch[1].to(device=device)

            # forward
            scores = model(data)
            _, predictions = scores.max(1)
            num_correct += (predictions == targets).sum()
            num_samples += predictions.size(0)
    
    return num_correct / num_samples

print(f'Accuracy on training set: {check_accuracy(train_loader, net)*100:.2f}%')
print(f'Accuracy on test set: {check_accuracy(test_loader, net)*100:.2f}%')

Accuracy on training set: 100.00%
Accuracy on test set: 100.00%


In [96]:
# Find the most important features of the model
# get the gradients of the model
net.eval()
gradients = []
for batch in train_loader:
    # get data to GPU if possible
    data = batch[0].to(device=device)
    targets = batch[1].to(device=device)

    # forward
    scores = net(data)
    loss = criterion(scores, targets)
    loss.backward()
    gradients.append(net.fc1.weight.grad.detach().cpu().numpy())

# average the gradients
gradients = np.mean(gradients, axis=0)
print(gradients.shape)

# print(len(gradients))
# print(len(gradients[0]))
# print(len(gradients[0][0]))

# find the indices of the 10 most important features
most_important_gradients_0 = gradients[0].argsort()[-10:][::-1]
most_important_gradients_1 = gradients[1].argsort()[-10:][::-1]

# print the 10 most important features
print(most_important_gradients_0.shape)
print(most_important_gradients_0)
print(gradients[0][most_important_gradients_0])

print(most_important_gradients_1.shape)
print(most_important_gradients_1)
print(gradients[1][most_important_gradients_1])

(2, 768)
(10,)
[308 752 381 522 667 701 109 282  41 430]
[0.00937229 0.00321044 0.00270355 0.00249884 0.00202032 0.00197234
 0.001949   0.00188883 0.0018535  0.00183217]
(10,)
[601 721 161 333 205 346 708 576 131 446]
[0.00233819 0.00205217 0.00204614 0.00201515 0.00188911 0.0017302
 0.00169615 0.0016606  0.00159734 0.00159162]


In [97]:
combined_importance_grad = list(set(list(most_important_gradients_0) + list(most_important_gradients_1)))
print(combined_importance_grad)
print(len(combined_importance_grad))

[131, 522, 282, 667, 161, 41, 430, 308, 701, 446, 576, 708, 333, 205, 721, 601, 346, 109, 752, 381]
20


In [98]:
# Find the most important features for the model
# get the weights of the fully connected layer
weights = net.fc1.weight.data.cpu().numpy()

# find the indices of the 10 most important features
most_important_features_0 = weights[0].argsort()[-10:][::-1]
most_important_features_1 = weights[1].argsort()[-10:][::-1]

# print the 10 most important features and their weights
print(most_important_features_0.shape)
print(most_important_features_0)
print(weights[0][most_important_features_0])

print(most_important_features_1.shape)
print(most_important_features_1)
print(weights[1][most_important_features_1])

(10,)
[672 628 705 558 633 719 605 446 343 158]
[0.42129228 0.37351102 0.3513944  0.3392098  0.3341787  0.32714713
 0.32431948 0.3039584  0.29635397 0.29567194]
(10,)
[442 314 603 489 282 289 630 715 112 751]
[0.3931066  0.3693206  0.3682808  0.36532345 0.35652688 0.34640998
 0.34001842 0.33912355 0.32210195 0.321611  ]


In [99]:
combined_importance = list(set(list(most_important_features_0) + list(most_important_features_1)))
print(combined_importance)
print(len(combined_importance))

[282, 158, 672, 289, 558, 314, 442, 446, 705, 715, 719, 343, 603, 605, 489, 751, 112, 628, 630, 633]
20


In [100]:
class Net_small(nn.Module):
    def __init__(self):
        super(Net_small, self).__init__()
        self.fc1 = nn.Linear(20, 2)

    def forward(self, x):
        # apply relu on the output of the fully connected layer
        x = F.relu(self.fc1(x))
        return x

In [101]:
# create datasets with the 20 most important features
df_train_small = pd.DataFrame({
    'word': df_train['word'],
    'embedding': df_train['embedding'].apply(lambda x: [x[i] for i in combined_importance]),
    'label': df_train['label']
})

df_test_small = pd.DataFrame({
    'word': df_test['word'],
    'embedding': df_test['embedding'].apply(lambda x: [x[i] for i in combined_importance]),
    'label': df_test['label']
})

print(df_train_small[:5])
print(df_train_small[-5:])
print(df_test_small[:5])
print(df_test_small[-5:])

print("\nLength of reduced embedding: ", len(df_train_small['embedding'].tolist()[0]))

    word                                          embedding  label
0    job  [-0.16747981309890747, 0.47371211647987366, 0....      1
1   body  [0.19887007772922516, 0.2644270360469818, 0.04...      1
2  faith  [-0.09121094644069672, -0.2395203709602356, 0....      1
3  earth  [0.118535615503788, -0.03201966732740402, 0.08...      1
4  water  [-0.38860055804252625, 0.08342357724905014, 0....      1
          word                                          embedding  label
181   somebody  [-0.30281540751457214, 0.24308684468269348, 0....      0
182         in  [-0.4305441677570343, 0.04467826336622238, 0.1...      0
183         on  [-0.3543335199356079, -0.263896107673645, 0.03...      0
184      later  [0.024935398250818253, 0.14524027705192566, 0....      0
185  something  [-0.48253750801086426, 0.1732560396194458, -0....      0
     word                                          embedding  label
0    mind  [0.11320915818214417, 0.18943685293197632, 0.0...      1
1   smile  [-0.281272232

In [102]:
# create datasets
train_dataset_small = CustomDataset(df_train_small['embedding'], df_train_small['label'])
test_dataset_small = CustomDataset(df_test_small['embedding'], df_test_small['label'])

# create dataloaders
train_loader_small = DataLoader(train_dataset_small, batch_size=16, shuffle=True)
test_loader_small = DataLoader(test_dataset_small, batch_size=16, shuffle=True)

In [109]:
# train the model
net2 = Net_small()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.003)

num_epochs = 100
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
net2.to(device)

for epoch in range(num_epochs):
    net2.train()
    combined_loss = 0
    for batch in train_loader_small:
        # get data to GPU if possible
        data = batch[0].to(device=device)
        targets = batch[1].to(device=device)

        # forward
        scores = net2(data)
        loss = criterion(scores, targets)
        combined_loss += loss.item()

        # backward
        optimizer.zero_grad()
        loss.backward()

        # gradient descent or adam step
        optimizer.step()
    
    # print initial loss
    if epoch == 0:
        print(f'Initial loss: {combined_loss/len(train_loader_small)}')
        
    # print average loss per epoch every 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f'Epoch {epoch + 1}, loss={combined_loss/len(train_loader_small)}')
        # print(combined_loss / len(train_loader))


Initial loss: 0.682785709698995
Epoch 10, loss=0.6843173752228419
Epoch 20, loss=0.6837831139564514
Epoch 30, loss=0.6835499952236811
Epoch 40, loss=0.6837201118469238
Epoch 50, loss=0.684459904829661
Epoch 60, loss=0.6836973081032435
Epoch 70, loss=0.6828592220942179
Epoch 80, loss=0.684044341246287
Epoch 90, loss=0.6824019501606623
Epoch 100, loss=0.683701162536939


In [104]:
# create datasets with the 20 most important features by gradients
df_train_small_grad = pd.DataFrame({
    'word': df_train['word'],
    'embedding': df_train['embedding'].apply(lambda x: [x[i] for i in combined_importance_grad]),
    'label': df_train['label']
})

df_test_small_grad = pd.DataFrame({
    'word': df_test['word'],
    'embedding': df_test['embedding'].apply(lambda x: [x[i] for i in combined_importance_grad]),
    'label': df_test['label']
})

print(df_train_small_grad[:5])
print(df_train_small_grad[-5:])
print(df_test_small_grad[:5])
print(df_test_small_grad[-5:])

print("\nLength of reduced embedding: ", len(df_train_small_grad['embedding'].tolist()[0]))

    word                                          embedding  label
0    job  [0.5783542990684509, -0.08179537951946259, -0....      1
1   body  [0.2662411034107208, -0.5605854392051697, 0.19...      1
2  faith  [0.3823331594467163, -0.22967687249183655, -0....      1
3  earth  [0.22662444412708282, -0.48906248807907104, 0....      1
4  water  [-0.036070797592401505, -0.42757871747016907, ...      1
          word                                          embedding  label
181   somebody  [0.4352976679801941, -0.2624276280403137, -0.3...      0
182         in  [0.33432042598724365, -0.49227994680404663, -0...      0
183         on  [0.4110128879547119, -0.5570359230041504, -0.3...      0
184      later  [0.2996409237384796, -0.44795429706573486, 0.0...      0
185  something  [0.4520237445831299, -0.44595324993133545, -0....      0
     word                                          embedding  label
0    mind  [0.0946241021156311, -0.20241917669773102, 0.1...      1
1   smile  [-0.130511417

In [105]:
# create datasets
train_dataset_small_grad = CustomDataset(df_train_small_grad['embedding'], df_train_small_grad['label'])
test_dataset_small_grad = CustomDataset(df_test_small_grad['embedding'], df_test_small_grad['label'])

# create dataloaders
train_loader_small_grad = DataLoader(train_dataset_small_grad, batch_size=16, shuffle=True)
test_loader_small_grad = DataLoader(test_dataset_small_grad, batch_size=16, shuffle=True)

In [108]:
# train the model
net3 = Net_small()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.003)

num_epochs = 100
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
net3.to(device)

for epoch in range(num_epochs):
    net3.train()
    combined_loss = 0
    for batch in train_loader_small_grad:
        # get data to GPU if possible
        data = batch[0].to(device=device)
        targets = batch[1].to(device=device)

        # forward
        scores = net3(data)
        loss = criterion(scores, targets)
        combined_loss += loss.item()

        # backward
        optimizer.zero_grad()
        loss.backward()

        # gradient descent or adam step
        optimizer.step()
    
    # print initial loss
    if epoch == 0:
        print(f'Initial loss: {combined_loss/len(train_loader_small_grad)}')
        
    # print average loss per epoch every 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f'Epoch {epoch + 1}, loss={combined_loss/len(train_loader_small_grad)}')
        # print(combined_loss / len(train_loader))


Initial loss: 0.6651087254285812
Epoch 10, loss=0.6638975292444229
Epoch 20, loss=0.6628724982341131
Epoch 30, loss=0.6649783452351888
Epoch 40, loss=0.6622126897176107
Epoch 50, loss=0.6649622370799383
Epoch 60, loss=0.6641809791326523
Epoch 70, loss=0.6631830135981241
Epoch 80, loss=0.6627187331517538
Epoch 90, loss=0.6652914732694626
Epoch 100, loss=0.6618634164333344
